Feat/signup
benhurfaria/Magnus-Hur-sStoreBackEnd pull request #1
Opened 2021-11-09 22:37 UTC by benhurfaria

2021-11-11 11:26 UTC, Audamon requested changes

2021-11-11 11:26 UTC, Audamon commented on src/app.js
>  );
remover

2021-11-11 11:26 UTC, Audamon commented on src/app.js
> +})
remover

2021-11-11 11:26 UTC, Audamon commented on src/tests/signup.test.js
> +        console.log(validBody.email);
remover

2021-11-11 11:26 UTC, Audamon commented on src/tests/signup.test.js
> +    console.log(validBody.email);
remover

2021-11-11 11:26 UTC, Audamon commented on src/tests/signup.test.js
> +    console.log(validBody.email);
remover

2021-11-12 06:52 UTC, FranciscaFigueiredo approved these changes

2021-11-12 12:49 UTC, Audamon approved these changes

2021-11-12 12:49 UTC, merged